# Generated by Django 5.2.17 on 2026-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_project_image_url_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
